# version: "3.8"

services:
    web:
        build: .
        command: python app.py
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            - APP_SETTINGS=config.DevelopmentConfig
            - DATABASE_URL=postgresql://flask:password@db/flask_app
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - db
            - redis

    db:
        image: postgres:12
        restart: always
        environment:
            - POSTGRES_USER=arman
            - POSTGRES_PASSWORD=Iamarman1khan
            - POSTGRES_DB=arman
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis:7
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    worker:
    build: .
    command: rq worker --url redis://redis:6379/0
    depends_on:
        - redis
        - db
    
    environment:
    - APP_SETTINGS=config.DevelopmentConfig
    - DATABASE_URL=postgresql://arman:Iamarman1khan@db/arman
    - REDIS_URL=redis://redis:6379/0
volumes:
    postgres_data:
    redis_data:
